# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 UDPcheck authors
# fail2ban: строки PROBE из журнала замедлителя роботов (ops/udpcheck-tarpit.py). Их пишет только он и только для запросов, похожих на атаку.
# Положить в /etc/fail2ban/filter.d/udpcheck-probe.conf. Строка: «PROBE <адрес> <запрос с пробелами, замененными на _>». Адрес всегда идёт первым
# и проверен службой, поэтому подделать чужой адрес через текст запроса нельзя.
[Definition]
failregex = ^\s*\S+ \S+\[\d+\]: PROBE <HOST> \S*$
ignoreregex =
