# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 UDPcheck authors
"""Тексты интерфейса сайта на двух языках. Сборка (build_site.py) подставляет их в siteparts/index.tpl.html.

Правила: в значениях можно использовать {имя} (подставляется из кода) и HTML только в ключах, которые вставляются как HTML (ссылки, <b>).
@@LP@@ в ссылках заменяется на префикс языка ("" для русского, "/en" для английского). Склоняемые слова (u_*) заданы списком форм:
русский [1, 2-4, 5+], английский [1, остальные]. Русские тексты сверены с эталоном tests/i18n/golden_ru.json: менять их можно только осознанно.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RU_HTML = json.load(open(os.path.join(HERE, "ru_html.json"), encoding="utf-8"))
RU_HTML.update({
    "langsw_title": "English version", "langsw_label": "EN",
    "langhint_text": "This site is also available in English.", "langhint_link": "English", "langhint_close": "Close",
})

EN_HTML = {
    "title": "UDPcheck: is your ISP blocking UDP?",
    "meta_desc": "Find out whether your ISP blocks UDP from abroad and where the route breaks. Ready-made text for your ISP's support.",
    "nav_providers": "Providers", "nav_journal": "Journal", "nav_who": "Who is who", "nav_nodes": "Nodes", "nav_node": "Your own node",
    "h1": "Is your ISP blocking UDP?",
    "noscript": "This site needs JavaScript: the check runs in your browser.",
    "lead": "Press the button to find out whether UDP is blocked. If it is, you get ready-made text for your ISP's support with the place where the route breaks.",
    "btn_go": "Check my network",
    "hint": "Turn off your VPN and any bypass tools, otherwise the check measures them, not your ISP. Takes about 10 seconds.",
    "consent": 'By pressing the button you agree to the <a href="@@LP@@/terms">terms</a> and the <a href="@@LP@@/privacy">privacy policy</a>: during the check the service uses your IP address, it is not written to the database.',
    "routes_summary": "Routes to you in detail",
    "h2_providers": "Providers",
    "providers_help": "Status based on node measurements and visitor checks over the last 6 hours. The chart shows the share of measurements where UDP from abroad does not pass. Click a card for a detailed chart, results per server and routes. A provider card appears on its own as soon as a check is made in its network or a node comes online.",
    "search_ph": "Search: name or AS number", "search_aria": "Search providers", "loading": "Loading…",
    "host_summary": 'Hosting and VPN: <span id="hostcount"></span>',
    "host_help": "This is where checks made with a VPN on or from servers end up: the address belongs to a hosting company, not an ordinary ISP, so they are not part of the main list.",
    "h2_journal": "Journal",
    "journal_help": "When a provider's picture changed: the network appeared in checks for the first time, its status changed, or one of the checks showed blocking where there was none before. Hosting and VPN networks are not shown here.",
    "h2_who": "Who is who",
    "step1_b": "You", "step1_s": "You press the button. Your browser sends UDP to our servers and asks whether they received the requests, while the servers trace the route to you.",
    "step2_b": "Node: asks", "step2_s": "A volunteer's home computer or router. Every 15 minutes it sends packets out on its own and looks at whether replies came back. It checks its own network, where UDP is blocked.",
    "step3_b": "Anchor server: answers", "step3_s": "A server or VPS with a public IP. It receives packets and answers them, and checks nothing itself. It is the reference point inside the country and abroad.",
    "who_note": "The installer picks the role itself: a machine with a public IP becomes an anchor server, a home network becomes a node. The verdict “blocked or not” is built from the project's anchor servers. Volunteer servers take part in checks as independent witnesses: they can soften the verdict (“partially blocked”), but cannot accuse a provider on their own. In a country without project servers they serve as the reference point.",
    "h2_nodes": "Nodes and anchor servers", "h3_anchors": "Project anchor servers",
    "anchors_help": "For every visitor and node the reference points are the servers in their own country; all the others count as foreign.",
    "h3_refs": "Volunteer anchor servers", "h3_nodes": "Nodes",
    "h2_node": "Connect your own server or router",
    "node_intro": "One line for Linux and OpenWrt, root or sudo required. The installer picks the role itself: a <b>VPS or server with a public IP</b> becomes an anchor server (open UDP 47321, 47322 and TCP 47321), a <b>home network or router</b> becomes a node (nothing needs to be opened).",
    "cmd_install": "Install", "btn_copy": "Copy",
    "details_summary": "More: what the installer does, how to turn off the anchor role, uninstall, Windows",
    "details_text": 'It detects the system, installs Python if needed, downloads the agent and checks its SHA-256, and starts a service as an unprivileged user. It does not touch SSH or other services. It does not change the firewall: if the ports of the anchor role turn out to be closed, it shows which ones and offers to open them, but only with your consent. Before starting it shows the plan and waits 5 seconds (cancel with Ctrl+C). Code: <a href="/install-node.en.sh">install-node.en.sh</a>. If an anchor server is unreachable from outside (firewall, NAT), it stays inactive until the ports are opened.',
    "cmd_node": "Force the “node” role (checks its own network, listens to nothing)",
    "cmd_ref": "Force the “anchor server” role (only answers checks)",
    "cmd_uninstall": "Uninstall (service, files, token)",
    "cmd_windows": "Windows (PowerShell, Python 3.7+ required). On macOS the same via curl and python3",
    "details_proxy": "If a proxy, VPN or tunnel is on the path, the node notices it and such a measurement is not counted.",
    "h2_help": "No anchor in your country? Add a server",
    "help_intro": "For the service to compare “you” with “from abroad”, it needs an anchor server in your country. Until there is one, volunteer servers can play that role.",
    "help_li1": "You need a server or VPS in your country: Linux, public IPv4 (not behind NAT).",
    "help_li2": "Open UDP 47321, 47322 and TCP 47321 in the firewall.",
    "help_li3": "Run the installer line from the “Connect your own server” section: a server with a public IP becomes an anchor on its own. A minute later it appears in the list of volunteer anchor servers.",
    "help_note": "A volunteer server takes part in checks of visitors and nodes as an independent witness: it can soften the verdict (“partially blocked”) but cannot accuse a provider on its own. Where there are no project servers, it serves as the reference point. The server's IP becomes known to the nodes and to the browsers of the visitors it checks.",
    "h2_privacy": "What we see and store",
    "priv_li1": "Your IP is visible for the duration of the request, to build the route and identify the provider. <b>It is not written to the database.</b>",
    "priv_li2": "We store the provider's network number (ASN), country, approximate city and measurement results, for 60 days.",
    "priv_li3": "The page creates a random anonymous number in your browser: it is needed only for rate limits and for counting checks. It is not linked to you and does not collect device data. You can delete it by clearing the site data.",
    "priv_li4": "Public: statistics per provider and the list of nodes (callsign, network, number of measurements). No addresses or cities.",
    "priv_li5": "A volunteer anchor server: its IP is known to the hub, to the nodes the hub assigned this server to, and to the browsers of the visitors it helps check (up to two such servers per check). The server sees the IPs of nodes and visitors the same way any STUN server on the internet does. Traces to a visitor's address are not passed to it. A home node does not give its IP to anyone.",
    "priv_li6": 'Questions, data deletion, remarks about logos and provider names: <a href="mailto:draldrean@protonmail.com">draldrean@protonmail.com</a>.',
    "priv_li7": "This is a test project. Conclusions refer to the servers checked and to the moment of measurement.",
    "footer_attr": 'IP geolocation by <a href="https://db-ip.com">DB-IP.com</a> (<a href="https://creativecommons.org/licenses/by/4.0/" rel="noopener">CC BY 4.0</a>). City names: <a href="https://www.geonames.org">GeoNames</a> (<a href="https://creativecommons.org/licenses/by/4.0/" rel="noopener">CC BY 4.0</a>). Network names and types: <a href="https://stat.ripe.net">RIPEstat</a> (RIPE NCC) and <a href="https://www.peeringdb.com">PeeringDB</a>.',
    "footer_links": '<a href="@@LP@@/privacy">Privacy policy</a> · <a href="@@LP@@/terms">Terms</a> · <a href="/protocol.txt">Node protocol</a> · <a href="https://github.com/Dagart-xyz/udpcheck" rel="noopener">Source code (AGPL-3.0)</a> · Contact: <a href="mailto:draldrean@protonmail.com">draldrean@protonmail.com</a>',
    "notice_text": 'We use no cookies and no counters; the only thing stored in your browser is a random number for rate limits. <a href="@@LP@@/privacy">More</a>',
    "notice_btn": "Got it", "newver_text": "A new version of the site is available.", "newver_btn": "Refresh",
    "langsw_title": "Русская версия", "langsw_label": "RU",
    "langhint_text": "Этот сайт также доступен на русском.", "langhint_link": "Русский", "langhint_close": "Закрыть",
}

# ключи из HTML-части, которые нужны и коду страницы
JS_FROM_HTML = ["loading", "btn_copy"]

RU_JS = {
    "ago_lt2": "меньше двух минут назад", "ago_min": "{n} мин назад", "ago_h": "{n} ч назад",
    "verd_cut": "Режется", "verd_partial": "Режется частично", "verd_ok": "Не режется", "verd_unreliable": "Замер ненадёжен", "verd_noanchor": "Не на что опираться",
    "verd_in_cut_line": "UDP из-за рубежа до вас не доходит",
    "verd_in_cut_what": "Звонки, игры, QUIC и VPN по UDP с зарубежными серверами могут работать плохо или совсем не работать. Внутри страны UDP при этом идёт нормально.",
    "verd_out_cut_line": "UDP за рубеж от вас не уходит",
    "verd_out_cut_what": "Исходящий UDP к зарубежным серверам блокируется. До точки в вашей стране UDP идёт нормально.",
    "verd_partial_line": "UDP проходит не ко всем зарубежным серверам",
    "verd_partial_what": "К части серверов UDP идёт, к другим нет: фильтр выборочный.",
    "verd_ok_line": "UDP проходит и внутри страны, и из-за рубежа",
    "verd_ok_what": "Блокировки UDP на проверенных серверах не видно.",
    "verd_ctrl_bad_line": "контрольная точка в вашей стране не прошла",
    "verd_ctrl_bad_what": "Вывод по зарубежным серверам в этом случае недостоверен.",
    "verd_ctrl_down_line": "контроль в вашей стране не ответил",
    "verd_unstable_line": "запросы к разным серверам вышли с разных адресов",
    "verd_unstable_what": "Так бывает при раздельной маршрутизации, VPN, прокси, а у некоторых операторов просто из-за устройства сети. Честно сравнить серверы нельзя, в общую статистику такой результат не передаётся.",
    "verd_noanchor_line": "в вашей стране у проекта нет опорного сервера",
    "verd_noanchor_what": "Нет опорного сервера в вашей стране, поэтому сравнить «у вас» и «из-за рубежа» нельзя. Вы можете помочь: добавьте сервер из вашей страны.",
    "verd_noforeign_line": "зарубежные серверы не ответили",
    "help_link_default": "Как добавить сервер", "help_how_help": "Как помочь", "help_how_add": "Как добавить", "help_how_service": "Как помочь сервису",
    "size_cut_text": "Короткие ответы проходят, а длинные ({big} байт) от {n} {servers} не доходят. Похоже, UDP режут по размеру пакета. Но причина может быть и в порту: длинные ответы идут с портов {ports}.",
    "size_part_text": "Длинные ответы доходят не всегда (часть потеряна): возможна порезка по размеру пакета или просто нестабильная связь.",
    "size_ok_text": "Длинные ответы (до {max} байт) тоже доходят.",
    "comm_name": "{country}, сервер добровольца",
    "web_title": "UDP-проверка прямо из вашего браузера",
    "web_running": "Шлём несколько маленьких UDP-запросов на наши серверы и ждём ответы…",
    "web_unsupported": "Ваш браузер не поддерживает WebRTC, поэтому проверку из браузера сделать нельзя.",
    "web_error": "Не удалось получить список серверов для проверки.",
    "web_explain": "Каждый сервер получает несколько маленьких UDP-запросов и должен ответить. Ответ дошёл до вас: входящий UDP с этого сервера проходит. Затем серверы проекта отвечают длинными пакетами (600 и 1200 байт) с других портов: так видно, не режут ли UDP по размеру. Тест слабее замера узла (мало пакетов, нет потока).",
    "web_home": "в вашей стране", "web_foreign": "из-за рубежа", "web_answers": "ответов {ok} из {n}",
    "web_witness": "свидетель: сам вывод не определяет",
    "web_seen_lost": "входящий UDP от этого сервера до вас не доходит: он получил ваши запросы и отправил ответы",
    "web_seen_got": "сервер ваши запросы получил",
    "web_seen_none": "исходящий UDP до этого сервера не доходит: запросы не дошли",
    "web_pad": "длинные ответы: {list}", "web_pad_item": "{size} Б: {ok} из {n}",
    "web_mixed": "Серверы увидели вас с разных внешних адресов, поэтому проверка не сравнивает провайдера честно. В статистику она не передана.",
    "web_seen_failed": "Подтверждение от серверов, дошли ли ваши запросы, получить не удалось: о направлении потери судить нельзя.",
    "web_ctrl_bad": "Серверы в вашей стране не ответили: возможно, включён VPN, браузер блокирует WebRTC или проблема с сетью. Вывод ненадёжен.",
    "web_noanchor": "В вашей стране у нас пока нет опорного сервера, сравнивать не с чем.",
    "ans_nodata": "Нет данных", "ans_noref": "Нет точки отсчёта",
    "tcp_ok_note": "TCP до тех же серверов при этом проходит: не работает именно UDP.",
    "ans_prelim": "Предварительно", "ans_by_nodes": "По данным узлов",
    "ans_basis": "Основание: {rounds} {meas} от {nodes} {nodew} вашего провайдера за 24 часа, такой итог в {top} из {rounds}. Последний замер: {last}.",
    "ans_weak_note": "Данных мало: нужно хотя бы 2 узла и 5 замеров для уверенного вывода.",
    "ans_by_browser": "По проверке в вашем браузере",
    "ans_browser_note": "У вашего провайдера пока нет узлов, ответ основан на UDP-проверке из браузера (несколько маленьких пакетов, слабее замера узла)",
    "ans_long_big": "Режутся длинные пакеты", "ans_long_line": "короткие UDP-ответы доходят, длинные нет",
    "ans_long_unchecked": "Длинные пакеты и сплошной поток не проверялись",
    "ans_unknown_big": "Пока не знаем", "ans_unknown_line": "у вашего провайдера нет узлов, прямой проверки UDP нет",
    "ans_unknown_what": "Маршруты и текст для техподдержки ниже всё равно можно использовать. Чтобы получить точный ответ, подключите узел (раздел «Свой узел») или попросите кого-то с тем же провайдером.",
    "ans_isp": "Ваш провайдер по базе IP: {isp}", "ans_isp_unknown": "не определён", "ans_city": "{city} (приблизительно)",
    "ans_browser_now": "Проверка в вашем браузере прямо сейчас: {verdict}.",
    "list_and": "и",
    "cm_prov_unknown": "оператор не определён",
    "cm_subject": "Тема: не проходит входящий UDP-трафик из-за рубежа (проверка {date}, {tz})",
    "cm_greeting": "Добрый день. Моё подключение к интернету: {prov}. Прошу рассмотреть обращение по существу.",
    "cm_problem_part": "Проблема: UDP-пакеты от части серверов за рубежом до меня не доходят ({bad}), ответы на мои UDP-запросы к ним не приходят. До остальных зарубежных серверов и до серверов внутри моей страны UDP доходит.",
    "cm_problem_all": "Проблема: UDP-пакеты от серверов за рубежом до меня не доходят, ответы на мои UDP-запросы к ним не приходят. От серверов внутри моей страны UDP доходит.",
    "cm_what": "Что показала проверка независимыми серверами проекта dagart.xyz (выполнена при выключенных VPN и прокси):",
    "cm_home": "Серверы в моей стране ({cities}): ответов на мои UDP-запросы {ok} из {n}. Канал работает.",
    "cm_foreign": "Зарубежные серверы: {list}.", "cm_foreign_item": "{name}: {ok} из {n}",
    "cm_got": "Эти серверы подтверждают, что мои запросы получили{replied} ({cities}), а ответы до меня не дошли: потеряно именно движение к моему адресу из-за рубежа.",
    "cm_got_replied": " и отправили на них ответы",
    "cm_nodes": "Узлы проекта в вашей сети ({n} {nodes}): в {top} из {rounds} замеров за сутки {tail}",
    "cm_nodes_in": "пакеты до зарубежных серверов доходят (серверы это подтверждают), а ответы обратно не приходят.",
    "cm_nodes_part": "UDP до части зарубежных серверов не проходит.",
    "cm_tcp": "TCP до тех же зарубежных серверов с узлов проекта в вашей сети проходит ({ok} из {total} проверок, данные передаются в обе стороны): серверы и маршрут доступны, не работает именно UDP.",
    "cm_long": "За {span} наблюдений: {cut} из {total} замеров узлов проекта в вашей сети с тем же результатом.",
    "cm_routes": "Маршруты от зарубежных серверов до моего адреса замолкают: {list}. Дальше, до меня, ответов нет.{stale}",
    "cm_route_item": "{cities} — {where}{as}", "cm_in_net": "внутри вашей сети ", "cm_in_as": "в сети ",
    "cm_stale": "Маршруты сняты {date}.",
    "cm_why1": "Почему это не авария: серверы в моей стране отвечают в тот же момент, то есть канал работает",
    "cm_why_tcp": ", а TCP до тех же зарубежных серверов проходит",
    "cm_why2": "; теряется один вид трафика (UDP из-за рубежа)",
    "cm_why_countries": ", причём сразу от серверов в {n} {countries} ({list}), которые друг от друга не зависят",
    "cm_why_long": ", и так продолжается {span}",
    "cm_why_end": ". Если вы считаете это аварией, укажите её номер, время начала и срок устранения.",
    "cm_ask": "Прошу ответить письменно:",
    "cm_q1": "Применяется ли на вашей сети или у вышестоящих операторов фильтрация входящего UDP из-за рубежа (в том числе оборудованием, установленным по требованию регулятора)?",
    "cm_q2": "Если нет, в каком месте, по вашим данным, теряются пакеты?",
    "cm_q3": "Когда доступ будет восстановлен в полном объёме?",
    "cm_foot": "Проверку можно повторить самостоятельно: https://dagart.xyz (кнопка «Проверить мою сеть»). Результаты по провайдерам открыты.",
    "sup_title": "Текст для техподдержки",
    "sup_noref": "Для вашей страны пока нет точки отсчёта, поэтому обращение к провайдеру подготовить нельзя.",
    "sup_unreliable": "Проверка из браузера ненадёжна: запросы к разным серверам вышли с разных адресов (раздельная маршрутизация, VPN, прокси). Обращение по такому результату готовить нельзя: повторите проверку с устройства, у которого весь трафик идёт одним путём.",
    "sup_none": "Блокировки UDP не видно, поэтому обращение провайдеру не нужно. Если связь всё же плохая, повторите проверку позже или запустите её без VPN.",
    "sup_ready": "Готов к отправке, ваши данные уже подставлены. Перед отправкой убедитесь, что VPN и прокси на устройстве выключены: текст на это ссылается.",
    "btn_copy_text": "Скопировать текст", "btn_copied": "Скопировано", "btn_again": "Проверить ещё раз", "btn_checking": "Проверяю…",
    "go_detecting": "Определяю провайдера и данные узлов…",
    "report_limited": "В общую статистику результат этого часа уже передан: лимит защищает её от накруток и общий для вашей сети. Ваш ответ выше от этого не зависит.",
    "me_error": "Не удалось получить данные узлов.",
    "trace_429": "Трассировку можно запускать не чаще раза в 5 минут (общий лимит для вашей сети). Повторите через {min} {minutes}.",
    "trace_error": "Не удалось запустить трассировку.", "net_error": "Нет связи с сервером. Проверьте интернет.",
    "rt_stale": "Новую трассировку можно будет запустить через {min} {minutes} (не чаще раза в 5 минут). Ниже маршруты, снятые {date}.",
    "rt_all_reach": "Маршруты со всех серверов доходят до вас.",
    "rt_home_only": "Из вашей страны маршрут до вас доходит, из-за рубежа нет: обрыв на пути между сетями, не у вас дома.",
    "rt_none": "Ни один маршрут, даже из вашей страны, не дошёл до вашего устройства до конца: домашний роутер и оборудование оператора обычно не отвечают на трассировку, хотя связь при этом работает. Поэтому по маршрутам вывод не делаем, ориентируйтесь на UDP-проверки выше.",
    "rt_from_home": "Из вашей страны", "rt_from_foreign": "Из-за рубежа", "rt_pending": "ждём результат…",
    "rt_timeout": "сервер не успел ответить", "rt_nodata": "нет данных", "rt_reached": "дошли до вас", "rt_silent": "дальше ответов нет",
    "pst_noanchor": "Нет опорного сервера в стране", "pst_cut": "Режется", "pst_partial": "Режется частично", "pst_ok": "Не режется", "pst_stale": "Нет свежих данных",
    "pst_old": "(давно)", "prov_sizecut": "⚠ длинные UDP-пакеты не проходят",
    "pf_hour": "за час: {n}", "pf_day": ";  сутки: {n}", "pf_web": " (из них посетителей: {n})", "pf_asns": ";  сетей оператора: {n}",
    "pf_last": ";  последний замер {ago}", "pf_weak": ";  мало данных",
    "jst_cut": "режется", "jst_partial": "режется частично", "jst_ok": "не режется", "jst_stale": "нет свежих данных", "jst_noanchor": "нет опорного сервера в стране",
    "j_ev": " (проверок за 6 часов: {checks}{browsers})", "j_ev_browsers": ", браузеров: {n}",
    "j_new": "впервые в проверках: {st}{ev}", "j_change": "{old} → {new}{ev}",
    "j_cc_many": "у посетителей ({n}) этой сети ", "j_cc_one": "у одного посетителя этой сети ",
    "j_cc_in": "входящий UDP из-за рубежа не доходит (из России доходит)",
    "j_cc_in_ok": ". Исходящий уходит: зарубежные серверы получили запросы и отправили ответы (серверов: {n})",
    "j_cc_out_cap": "Исходящий UDP за рубеж не уходит: зарубежные серверы запросов не получили",
    "j_cc_out": "исходящий UDP за рубеж не уходит: зарубежные серверы запросов не получили",
    "j_cc_tail": ". Причина может быть у провайдера или у самих посетителей", "j_cc_before": " (до этого: {st})",
    "j_size": "у посетителей ({n}) этой сети короткие UDP-пакеты проходят, а длинные ({size} байт) нет. Возможно, режут по размеру пакета",
    "journal_error": "Не удалось загрузить журнал.", "journal_empty": "Пока записей нет.",
    "prov_nothing": "Ничего не найдено. Если вашего провайдера нет в списке, нажмите «Проверить мою сеть»: он появится после проверки.",
    "prov_nodata": "Пока нет данных. Нажмите «Проверить мою сеть» или подключите узел, и ваш провайдер появится здесь.",
    "prov_more": "Показать ещё ↓", "prov_more_cnt": "{n} из {rest}", "load_error": "Не удалось загрузить данные.",
    "tst_ok": "чисто", "tst_incut": "ответы не приходят", "tst_outcut": "до сервера не доходит", "tst_part": "на части портов",
    "tst_mixed": "смешанно", "tst_lossy": "с потерями", "tst_nodata": "нет данных",
    "pd_back": "← Все провайдеры", "pd_404": "По этой сети пока нет данных.", "title_suffix": ": режет ли UDP | UDPcheck",
    "pd_nets": "Сети оператора: {list}",
    "pd_tag_hosting": "хостинг или VPN, не обычный провайдер", "pd_tag_old": "данные устарели: замеров за последние 6 часов нет",
    "pd_tag_weak": "мало данных: нужно хотя бы 5 замеров или проверок",
    "pd_size_bad": "Длинные UDP-пакеты (до {max} байт) не доходят у {cut} из {tested} посетителей за сутки, а короткие доходят. Возможно, режут по размеру пакета.",
    "pd_size_ok": "Длинные UDP-пакеты (до 1200 байт) доходят: проверено у {tested} {visitors} за сутки.",
    "pd_hour": "за час", "pd_day": "за сутки", "pd_week": "за 7 суток", "pd_nodes": "узлов за сутки", "pd_web": "проверок посетителей за сутки",
    "pd_last": "последний замер: {ago}",
    "pd_typical": "Типичный итог за сутки ({top} из {rounds} замеров): {txt}",
    "pd_changes": "Как менялась картина",
    "pd_changes_help": "Каждый столбик — один час. Красная часть — доля замеров, где UDP из-за рубежа не проходит, зелёная — проходит, серая — замеры ненадёжны.",
    "pd_ago24": "24 часа назад", "pd_ago7d": "7 суток назад", "pd_now": "сейчас", "pd_24h": "24 часа", "pd_7d": "7 суток",
    "pd_history": "История статуса", "pd_servers": "До каких серверов доходит UDP (за сутки)", "pd_nodata": "Пока нет данных.",
    "pd_control": "(контроль: та же страна, что у провайдера)", "pd_tcp": "TCP: {ok} из {total}",
    "pd_cuts": "Где замолкают маршруты (за 7 суток)", "pd_cut_foreign": "из-за рубежа", "pd_cut_home": "из страны провайдера",
    "pd_cuts_none": "Трассировок пока нет.",
    "pd_cuts_note": "Обрыв в трассировке не доказывает, что режет именно эта сеть: домашнее и пограничное оборудование часто не отвечает на трассировку. Если маршруты из страны провайдера замолкают там же, это нормально.",
    "pd_nodes_title": "Узлы в этой сети", "pd_nodes_none": "сейчас нет узлов на связи",
    "pd_web_line": "Проверок из браузера посетителей за сутки: {wn}, из них с блокировкой: {wc}.",
    "pd_disclaimer": "Это автоматические измерения: они показывают, проходит ли UDP между сетью и серверами проекта в момент замера. Причина потерь может быть не у провайдера (транзитные сети, оборудование и настройки пользователей). Подробнее в условиях использования. Нашли ошибку или хотите уточнить данные: draldrean@protonmail.com.",
    "pd_terms": "Условия использования", "pd_cta": "Вы в этой сети? Проверить своё подключение", "pd_net_error": "Нет связи с сервером.",
    "nodes_error": "Не удалось загрузить список узлов.", "nd_country_unknown": "Страна не определена",
    "nd_active": "активен", "nd_silent": "не отвечает хабу", "nd_anchor_checks": "проверок посетителей за сутки: {checks}, ответил: {ok}",
    "nd_nodes_sum": "Узлов в сети: {n}, сейчас на связи: {on}.", "nd_nodes_none": "Пока ни одного узла. Станьте первым: команда ниже.",
    "nd_refs_sum": "Серверов добровольцев: {n}, активных: {a}.", "nd_refs_none": "Пока нет. Добавьте сервер: команда ниже.",
    "nd_inactive": "не активен", "nd_outdated": "есть новая версия агента",
    "nd_outdated_title": "Обновить можно той же командой установки. Старая версия продолжит работать.",
    "nd_isp_unknown": "провайдер не определён", "nd_place_unknown": "место не определено", "nd_online": "на связи", "nd_offline": "не на связи",
    "nd_ref_checks": "проверок за сутки {checks}, чисто {ok}", "nd_rounds": "замеров: {n}", "nd_tunnel": "(ещё {n} отбраковано из-за прокси)",
    "u_server_of": ["сервера", "серверов", "серверов"], "u_measure": ["замер", "замера", "замеров"], "u_node_of": ["узла", "узлов", "узлов"],
    "u_node_nom": ["узел", "узла", "узлов"], "u_hour": ["час", "часа", "часов"], "u_day": ["сутки", "суток", "суток"],
    "u_minute_acc": ["минуту", "минуты", "минут"], "u_country_in": ["стране", "странах", "странах"],
    "u_visitor_of": ["посетителя", "посетителей", "посетителей"], "u_server_nom": ["сервер", "сервера", "серверов"],
}

EN_JS = {
    "ago_lt2": "less than two minutes ago", "ago_min": "{n} min ago", "ago_h": "{n} h ago",
    "verd_cut": "Blocked", "verd_partial": "Partially blocked", "verd_ok": "Not blocked", "verd_unreliable": "Measurement unreliable", "verd_noanchor": "Nothing to compare with",
    "verd_in_cut_line": "UDP from abroad does not reach you",
    "verd_in_cut_what": "Calls, games, QUIC and UDP-based VPNs with foreign servers may work badly or not at all. Inside the country UDP works normally.",
    "verd_out_cut_line": "UDP to abroad does not leave you",
    "verd_out_cut_what": "Outbound UDP to foreign servers is blocked. UDP to the reference point in your country works normally.",
    "verd_partial_line": "UDP passes, but not to all foreign servers",
    "verd_partial_what": "UDP reaches some servers and not others: the filter is selective.",
    "verd_ok_line": "UDP passes both inside the country and from abroad",
    "verd_ok_what": "No UDP blocking is visible on the servers checked.",
    "verd_ctrl_bad_line": "the control point in your country failed",
    "verd_ctrl_bad_what": "In this case the conclusion about foreign servers is not reliable.",
    "verd_ctrl_down_line": "the control in your country did not answer",
    "verd_unstable_line": "requests to different servers left from different addresses",
    "verd_unstable_what": "This happens with split routing, VPNs and proxies, and with some operators simply because of how their network is built. The servers cannot be compared fairly, and such a result is not sent to the overall statistics.",
    "verd_noanchor_line": "the project has no anchor server in your country",
    "verd_noanchor_what": "There is no anchor server in your country, so “you” cannot be compared with “from abroad”. You can help: add a server from your country.",
    "verd_noforeign_line": "foreign servers did not answer",
    "help_link_default": "How to add a server", "help_how_help": "How to help", "help_how_add": "How to add", "help_how_service": "How to help the service",
    "size_cut_text": "Short replies pass, but long ones ({big} bytes) from {n} {servers} do not arrive. UDP looks cut by packet size. But the reason may also be the port: long replies come from ports {ports}.",
    "size_part_text": "Long replies do not always arrive (some are lost): packet-size filtering is possible, or the connection is simply unstable.",
    "size_ok_text": "Long replies (up to {max} bytes) arrive as well.",
    "comm_name": "{country}, volunteer server",
    "web_title": "UDP check right from your browser",
    "web_running": "Sending a few small UDP requests to our servers and waiting for replies…",
    "web_unsupported": "Your browser does not support WebRTC, so the browser check cannot be done.",
    "web_error": "Could not get the list of servers to check.",
    "web_explain": "Each server gets a few small UDP requests and must answer. A reply reaching you means inbound UDP from that server passes. Then the project's servers answer with long packets (600 and 1200 bytes) from other ports: this shows whether UDP is cut by size. The test is weaker than a node measurement (few packets, no stream).",
    "web_home": "in your country", "web_foreign": "from abroad", "web_answers": "replies {ok} of {n}",
    "web_witness": "witness: does not decide the verdict itself",
    "web_seen_lost": "inbound UDP from this server does not reach you: it received your requests and sent replies",
    "web_seen_got": "the server received your requests",
    "web_seen_none": "outbound UDP to this server does not pass: the requests did not arrive",
    "web_pad": "long replies: {list}", "web_pad_item": "{size} B: {ok} of {n}",
    "web_mixed": "The servers saw you from different external addresses, so the check does not compare the provider fairly. It was not sent to the statistics.",
    "web_seen_failed": "Could not get the servers' confirmation of whether your requests arrived: the direction of the loss cannot be judged.",
    "web_ctrl_bad": "Servers in your country did not answer: a VPN may be on, the browser may block WebRTC, or the network has a problem. The conclusion is unreliable.",
    "web_noanchor": "We have no anchor server in your country yet, so there is nothing to compare with.",
    "ans_nodata": "No data", "ans_noref": "No reference point",
    "tcp_ok_note": "TCP to the same servers works, so exactly UDP is broken.",
    "ans_prelim": "Preliminary", "ans_by_nodes": "Based on node data",
    "ans_basis": "Basis: {rounds} {meas} from {nodes} {nodew} in your provider's network over 24 hours, this outcome in {top} of {rounds}. Last measurement: {last}.",
    "ans_weak_note": "Not much data: at least 2 nodes and 5 measurements are needed for a confident conclusion.",
    "ans_by_browser": "Based on your browser check",
    "ans_browser_note": "Your provider has no nodes yet, the answer rests on a UDP check from the browser (a few small packets, weaker than a node measurement)",
    "ans_long_big": "Long packets are blocked", "ans_long_line": "short UDP replies arrive, long ones do not",
    "ans_long_unchecked": "Long packets and a continuous stream were not checked",
    "ans_unknown_big": "Don't know yet", "ans_unknown_line": "your provider has no nodes, so there is no direct UDP check",
    "ans_unknown_what": "The routes and the support text below can still be used. For an exact answer, connect a node (the “Your own node” section) or ask someone with the same provider.",
    "ans_isp": "Your provider by IP database: {isp}", "ans_isp_unknown": "not identified", "ans_city": "{city} (approximate)",
    "ans_browser_now": "Your browser check right now: {verdict}.",
    "list_and": "and",
    "cm_prov_unknown": "operator not identified",
    "cm_subject": "Subject: inbound UDP traffic from abroad is not passing (checked {date}, {tz})",
    "cm_greeting": "Hello. My internet connection: {prov}. Please review this request on its merits.",
    "cm_problem_part": "Problem: UDP packets from some servers abroad do not reach me ({bad}), and replies to my UDP requests to them do not come back. UDP from the other foreign servers and from servers inside my country reaches me.",
    "cm_problem_all": "Problem: UDP packets from servers abroad do not reach me, and replies to my UDP requests to them do not come back. UDP from servers inside my country reaches me.",
    "cm_what": "What a check by the project's independent servers (dagart.xyz) showed (done with VPN and proxy turned off):",
    "cm_home": "Servers in my country ({cities}): replies to my UDP requests {ok} of {n}. The channel works.",
    "cm_foreign": "Foreign servers: {list}.", "cm_foreign_item": "{name}: {ok} of {n}",
    "cm_got": "These servers confirm that they received my requests{replied} ({cities}), and the replies did not reach me: exactly the traffic towards my address from abroad is lost.",
    "cm_got_replied": " and sent replies to them",
    "cm_nodes": "Project nodes in your network ({n} {nodes}): in {top} of {rounds} measurements over a day {tail}",
    "cm_nodes_in": "packets to foreign servers arrive (the servers confirm it), but replies do not come back.",
    "cm_nodes_part": "UDP to some of the foreign servers does not pass.",
    "cm_tcp": "TCP to the same foreign servers from project nodes in your network works ({ok} of {total} checks, data flows in both directions): the servers and the route are reachable, exactly UDP is broken.",
    "cm_long": "Over {span} of observations: {cut} of {total} measurements by project nodes in your network with the same result.",
    "cm_routes": "Routes from foreign servers to my address go silent: {list}. Beyond that, towards me, there are no replies.{stale}",
    "cm_route_item": "{cities} — {where}{as}", "cm_in_net": "inside your network ", "cm_in_as": "in the network ",
    "cm_stale": "Routes captured {date}.",
    "cm_why1": "Why this is not an outage: servers in my country answer at the same moment, so the channel works",
    "cm_why_tcp": ", and TCP to the same foreign servers works",
    "cm_why2": "; only one kind of traffic is lost (UDP from abroad)",
    "cm_why_countries": ", seen from servers in {n} {countries} at once ({list}), which do not depend on each other",
    "cm_why_long": ", and this has been going on for {span}",
    "cm_why_end": ". If you consider this an outage, please give its number, start time and expected resolution time.",
    "cm_ask": "Please reply in writing:",
    "cm_q1": "Is inbound UDP from abroad filtered on your network or by upstream operators (including by equipment installed at a regulator's request)?",
    "cm_q2": "If not, where, according to your data, are the packets lost?",
    "cm_q3": "When will access be restored in full?",
    "cm_foot": "You can repeat the check yourself: https://dagart.xyz/en/ (the “Check my network” button). Provider results are public.",
    "sup_title": "Text for support",
    "sup_noref": "There is no reference point for your country yet, so a request to the provider cannot be prepared.",
    "sup_unreliable": "The browser check is unreliable: requests to different servers left from different addresses (split routing, VPN, proxy). A request cannot be prepared from such a result: repeat the check from a device whose whole traffic takes one path.",
    "sup_none": "No UDP blocking is visible, so no request to the provider is needed. If the connection is still bad, repeat the check later or run it without a VPN.",
    "sup_ready": "Ready to send, your details are already filled in. Before sending, make sure VPN and proxy are off on your device: the text refers to it.",
    "btn_copy_text": "Copy text", "btn_copied": "Copied", "btn_again": "Check again", "btn_checking": "Checking…",
    "go_detecting": "Identifying the provider and node data…",
    "report_limited": "This hour's result has already been sent to the overall statistics: the limit protects them from inflation and is shared by your network. Your answer above does not depend on it.",
    "me_error": "Could not get node data.",
    "trace_429": "A trace can be started no more than once in 5 minutes (a limit shared by your network). Try again in {min} {minutes}.",
    "trace_error": "Could not start the trace.", "net_error": "No connection to the server. Check your internet.",
    "rt_stale": "A new trace can be started in {min} {minutes} (no more than once in 5 minutes). Below are the routes captured {date}.",
    "rt_all_reach": "Routes from all servers reach you.",
    "rt_home_only": "From your country the route reaches you, from abroad it does not: the break is on the path between networks, not at your home.",
    "rt_none": "No route, even from your country, reached your device to the end: a home router and the operator's equipment usually do not answer to traces, although the connection works. That is why we draw no conclusion from the routes; rely on the UDP checks above.",
    "rt_from_home": "From your country", "rt_from_foreign": "From abroad", "rt_pending": "waiting for the result…",
    "rt_timeout": "the server did not answer in time", "rt_nodata": "no data", "rt_reached": "reached you", "rt_silent": "no replies beyond this point",
    "pst_noanchor": "No anchor server in the country", "pst_cut": "Blocked", "pst_partial": "Partially blocked", "pst_ok": "Not blocked", "pst_stale": "No recent data",
    "pst_old": "(long ago)", "prov_sizecut": "⚠ long UDP packets do not pass",
    "pf_hour": "last hour: {n}", "pf_day": ";  day: {n}", "pf_web": " (of which visitors: {n})", "pf_asns": ";  operator networks: {n}",
    "pf_last": ";  last measurement {ago}", "pf_weak": ";  little data",
    "jst_cut": "blocked", "jst_partial": "partially blocked", "jst_ok": "not blocked", "jst_stale": "no recent data", "jst_noanchor": "no anchor server in the country",
    "j_ev": " (checks in 6 hours: {checks}{browsers})", "j_ev_browsers": ", browsers: {n}",
    "j_new": "first seen in checks: {st}{ev}", "j_change": "{old} → {new}{ev}",
    "j_cc_many": "for visitors ({n}) in this network, ", "j_cc_one": "for one visitor in this network, ",
    "j_cc_in": "inbound UDP from abroad does not arrive (from Russia it does)",
    "j_cc_in_ok": ". Outbound works: foreign servers received the requests and sent replies (servers: {n})",
    "j_cc_out_cap": "Outbound UDP abroad does not leave: foreign servers did not receive the requests",
    "j_cc_out": "outbound UDP abroad does not leave: foreign servers did not receive the requests",
    "j_cc_tail": ". The cause may be the provider or the visitors themselves", "j_cc_before": " (before: {st})",
    "j_size": "for visitors ({n}) in this network short UDP packets pass, but long ones ({size} bytes) do not. Packets may be cut by size",
    "journal_error": "Could not load the journal.", "journal_empty": "No entries yet.",
    "prov_nothing": "Nothing found. If your provider is not on the list, press “Check my network”: it will appear after the check.",
    "prov_nodata": "No data yet. Press “Check my network” or connect a node, and your provider will appear here.",
    "prov_more": "Show more ↓", "prov_more_cnt": "{n} of {rest}", "load_error": "Could not load the data.",
    "tst_ok": "clean", "tst_incut": "replies do not arrive", "tst_outcut": "does not reach the server", "tst_part": "on some ports",
    "tst_mixed": "mixed", "tst_lossy": "with losses", "tst_nodata": "no data",
    "pd_back": "← All providers", "pd_404": "No data for this network yet.", "title_suffix": ": is UDP blocked? | UDPcheck",
    "pd_nets": "Operator networks: {list}",
    "pd_tag_hosting": "hosting or VPN, not an ordinary provider", "pd_tag_old": "data is stale: no measurements in the last 6 hours",
    "pd_tag_weak": "little data: at least 5 measurements or checks needed",
    "pd_size_bad": "Long UDP packets (up to {max} bytes) do not arrive for {cut} of {tested} visitors over a day, while short ones do. Packets may be cut by size.",
    "pd_size_ok": "Long UDP packets (up to 1200 bytes) arrive: checked for {tested} {visitors} over a day.",
    "pd_hour": "last hour", "pd_day": "last day", "pd_week": "last 7 days", "pd_nodes": "nodes in the last day", "pd_web": "visitor checks in the last day",
    "pd_last": "last measurement: {ago}",
    "pd_typical": "Typical outcome over the day ({top} of {rounds} measurements): {txt}",
    "pd_changes": "How the picture changed",
    "pd_changes_help": "Each bar is one hour. The red part is the share of measurements where UDP from abroad does not pass, green means it passes, grey means the measurements are unreliable.",
    "pd_ago24": "24 hours ago", "pd_ago7d": "7 days ago", "pd_now": "now", "pd_24h": "24 hours", "pd_7d": "7 days",
    "pd_history": "Status history", "pd_servers": "Which servers UDP reaches (over a day)", "pd_nodata": "No data yet.",
    "pd_control": "(control: same country as the provider)", "pd_tcp": "TCP: {ok} of {total}",
    "pd_cuts": "Where routes go silent (over 7 days)", "pd_cut_foreign": "from abroad", "pd_cut_home": "from the provider's country",
    "pd_cuts_none": "No traces yet.",
    "pd_cuts_note": "A break in a trace does not prove that exactly this network blocks traffic: home and border equipment often does not answer to traces. If routes from the provider's own country go silent in the same place, that is normal.",
    "pd_nodes_title": "Nodes in this network", "pd_nodes_none": "no nodes online right now",
    "pd_web_line": "Browser checks by visitors over the last day: {wn}, of which with blocking: {wc}.",
    "pd_disclaimer": "These are automated measurements: they show whether UDP passes between the network and the project's servers at the moment of measurement. The cause of losses may not be the provider (transit networks, equipment and users' settings). More in the terms of use. If you found a mistake or want to clarify the data: draldrean@protonmail.com.",
    "pd_terms": "Terms of use", "pd_cta": "Are you in this network? Check your connection", "pd_net_error": "No connection to the server.",
    "nodes_error": "Could not load the list of nodes.", "nd_country_unknown": "Country not identified",
    "nd_active": "active", "nd_silent": "not answering the hub", "nd_anchor_checks": "visitor checks over a day: {checks}, answered: {ok}",
    "nd_nodes_sum": "Nodes in the network: {n}, online now: {on}.", "nd_nodes_none": "No nodes yet. Be the first: the command is below.",
    "nd_refs_sum": "Volunteer servers: {n}, active: {a}.", "nd_refs_none": "None yet. Add a server: the command is below.",
    "nd_inactive": "inactive", "nd_outdated": "new agent version available",
    "nd_outdated_title": "You can update with the same install command. The old version keeps working.",
    "nd_isp_unknown": "provider not identified", "nd_place_unknown": "location not identified", "nd_online": "online", "nd_offline": "offline",
    "nd_ref_checks": "checks over a day {checks}, clean {ok}", "nd_rounds": "measurements: {n}", "nd_tunnel": "({n} more discarded because of a proxy)",
    "u_server_of": ["server", "servers"], "u_measure": ["measurement", "measurements"], "u_node_of": ["node", "nodes"],
    "u_node_nom": ["node", "nodes"], "u_hour": ["hour", "hours"], "u_day": ["day", "days"],
    "u_minute_acc": ["minute", "minutes"], "u_country_in": ["country", "countries"],
    "u_visitor_of": ["visitor", "visitors"], "u_server_nom": ["server", "servers"],
}

HTML = {"ru": RU_HTML, "en": EN_HTML}


def js_dict(lang):
    base = RU_JS if lang == "ru" else EN_JS
    d = dict(base)
    for k in JS_FROM_HTML:
        d[k] = HTML[lang][k]
    return d
